import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const APPOINTMENT_SERVICE_NAME = "appointment-service";

export const DEFAULT_APPOINTMENT_PAGE_SIZE = 20;

export const MINIMUM_NOTICE_HOURS = 24;
export const CANCELLATION_POLICY_HOURS = 24;

export const APPOINTMENT_EVENTS = {
  APPOINTMENT_CREATED: EVENT_TYPES.APPOINTMENT_CREATED,
  APPOINTMENT_UPDATED: EVENT_TYPES.APPOINTMENT_UPDATED,
  APPOINTMENT_RESCHEDULED: EVENT_TYPES.APPOINTMENT_RESCHEDULED,
  APPOINTMENT_CANCELLED: EVENT_TYPES.APPOINTMENT_CANCELLED,
  AVAILABILITY_UPDATED: "availability.updated",
} as const;
