import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const BILLING_SERVICE_NAME = "billing-service";

export const DEFAULT_CURRENCY = "USD";

export const BILLING_EVENTS = {
  INVOICE_CREATED: EVENT_TYPES.INVOICE_CREATED,
  INVOICE_UPDATED: EVENT_TYPES.INVOICE_UPDATED,
  INVOICE_ISSUED: EVENT_TYPES.INVOICE_ISSUED,
  INVOICE_PAID: EVENT_TYPES.INVOICE_PAID,
  INVOICE_VOIDED: EVENT_TYPES.INVOICE_VOIDED,
  INVOICE_ITEM_ADDED: EVENT_TYPES.INVOICE_ITEM_ADDED,
  INVOICE_ITEM_UPDATED: EVENT_TYPES.INVOICE_ITEM_UPDATED,
  TAX_RATE_CREATED: EVENT_TYPES.TAX_RATE_CREATED,
  TAX_RATE_UPDATED: EVENT_TYPES.TAX_RATE_UPDATED,
} as const;
