#!/usr/bin/env sh
. "$(dirname -- "$0")/../../../.husky/_/husky.sh" 2>/dev/null || true

ROOT_DIR="$(git rev-parse --show-toplevel)"
TOOLING_DIR="$ROOT_DIR/infrastructure/developer-tooling-layer"

cd "$ROOT_DIR" || exit 1

pnpm exec commitlint \
  --config "$TOOLING_DIR/commitlint/commitlint.config.js" \
  --edit "$1"
