-- AlterEnum
ALTER TYPE "TenantStatus" ADD VALUE IF NOT EXISTS 'TRIALING';
ALTER TYPE "TenantStatus" ADD VALUE IF NOT EXISTS 'TRIAL_EXPIRED';

-- AlterTable
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "subscriptionPlan" TEXT;
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "trialStart" TIMESTAMP(3);
ALTER TABLE "tenants" ADD COLUMN IF NOT EXISTS "trialEnd" TIMESTAMP(3);
