FROM node:22-alpine
WORKDIR /app

COPY package.json ./
RUN npm install

COPY prisma ./prisma
COPY tsconfig.json ./
COPY src ./src

RUN npx prisma generate && npm run build

EXPOSE 4000
CMD ["node", "dist/server.js"]
