ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TENANT_OWNER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'BILLING_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'READ_ONLY';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ORG_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ORG_BILLING_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';

ALTER TABLE "users" ALTER COLUMN "tenantId" DROP NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "organizationId" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "permissionOverrides" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
