export {
  loadEnv,
  env,
  getValidatedEnv,
  fullEnvSchema,
  type LoadEnvOptions,
} from "./loader";

export {
  nodeEnvSchema,
  coreEnvSchema,
  authEnvSchema,
  tenantEnvSchema,
  patientEnvSchema,
  appointmentEnvSchema,
  notesEnvSchema,
  billingEnvSchema,
  paymentEnvSchema,
  communicationEnvSchema,
  reportingEnvSchema,
  eventBusEnvSchema,
  gatewayEnvSchema,
  gatewayServiceUrlsSchema,
  type CoreEnv,
  type AuthEnv,
  type TenantEnv,
  type PatientEnv,
  type AppointmentEnv,
  type NotesEnv,
  type BillingEnv,
  type PaymentEnv,
  type CommunicationEnv,
  type ReportingEnv,
  type EventBusEnv,
  type GatewayEnv,
  type FullEnv,
} from "./schema";
