import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const PATIENT_SERVICE_NAME = "patient-service";

export const DEFAULT_PATIENT_PAGE_SIZE = 20;

export const PATIENT_EVENTS = {
  PATIENT_CREATED: EVENT_TYPES.PATIENT_CREATED,
  PATIENT_UPDATED: EVENT_TYPES.PATIENT_UPDATED,
  PATIENT_DELETED: EVENT_TYPES.PATIENT_DELETED,
  MEDICAL_RECORD_UPDATED: EVENT_TYPES.MEDICAL_RECORD_UPDATED,
} as const;
