import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const NOTIFICATION_SERVICE_NAME = "notification-service";

export const DEFAULT_NOTIFICATIONS_PAGE_SIZE = 50;

export const NOTIFICATION_EVENTS = {
  CREATE: EVENT_TYPES.NOTIFICATION_CREATE,
  READ: EVENT_TYPES.NOTIFICATION_READ,
  BROADCAST: EVENT_TYPES.NOTIFICATION_BROADCAST,
} as const;

export const NOTIFICATION_TYPES = {
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_UPDATED: "APPOINTMENT_UPDATED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  NOTE_CREATED: "NOTE_CREATED",
  NOTE_UPDATED: "NOTE_UPDATED",
  INVOICE_GENERATED: "INVOICE_GENERATED",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  STAFF_ADDED: "STAFF_ADDED",
  ROLE_CHANGED: "ROLE_CHANGED",
  SYSTEM_BROADCAST: "SYSTEM_BROADCAST",
} as const;
