export const PROVIDER_SEEDS = [
  {
    slug: "google-calendar",
    name: "Google Calendar",
    category: "calendar",
    description: "Sync appointments with Google Calendar",
    authType: "oauth",
  },
  {
    slug: "stripe",
    name: "Stripe Billing",
    category: "billing",
    description: "Platform subscription and patient billing via Stripe",
    authType: "none",
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    category: "storage",
    description: "Upload clinical notes and documents to Dropbox",
    authType: "oauth",
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    category: "storage",
    description: "Store and share clinical documents on Google Drive",
    authType: "oauth",
  },
  {
    slug: "onedrive",
    name: "OneDrive",
    category: "storage",
    description: "Backup notes and files to Microsoft OneDrive",
    authType: "oauth",
  },
  {
    slug: "twilio",
    name: "Twilio",
    category: "communication",
    description: "Send SMS reminders and notifications via Twilio",
    authType: "apiKey",
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    category: "communication",
    description: "Transactional email delivery via SendGrid",
    authType: "apiKey",
  },
  {
    slug: "zoom",
    name: "Zoom",
    category: "telehealth",
    description: "Schedule and launch telehealth sessions with Zoom",
    authType: "oauth",
  },
  {
    slug: "physiotec",
    name: "Physiotec",
    category: "exercise",
    description: "Sync home exercise programs from Physiotec",
    authType: "apiKey",
  },
  {
    slug: "medbridge",
    name: "MedBridge",
    category: "exercise",
    description: "Import exercise programs and patient education from MedBridge",
    authType: "apiKey",
  },
] as const;
