export const ERROR_CODES = {
  AUTH: {
    INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  },
  TENANT: {
    NOT_FOUND: "TENANT_NOT_FOUND",
    ACCESS_DENIED: "TENANT_ACCESS_DENIED",
  },
  PATIENT: {
    NOT_FOUND: "PATIENT_NOT_FOUND",
    VALIDATION_FAILED: "PATIENT_VALIDATION_FAILED",
  },
  APPOINTMENT: {
    NOT_FOUND: "APPOINTMENT_NOT_FOUND",
    CONFLICT: "APPOINTMENT_CONFLICT",
    AVAILABILITY_CONFLICT: "AVAILABILITY_CONFLICT",
  },
  NOTES: {
    NOT_FOUND: "NOTE_NOT_FOUND",
    SOAP_NOTE_INVALID: "SOAP_NOTE_INVALID",
  },
  BILLING: {
    INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
    INVOICE_ALREADY_PAID: "INVOICE_ALREADY_PAID",
    INVOICE_INVALID_STATE: "INVOICE_INVALID_STATE",
  },
  PAYMENTS: {
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
    REFUND_FAILED: "REFUND_FAILED",
  },
  COMMUNICATION: {
    NOTIFICATION_FAILED: "NOTIFICATION_FAILED",
    REMINDER_FAILED: "REMINDER_FAILED",
  },
  REPORTING: {
    METRICS_NOT_FOUND: "METRICS_NOT_FOUND",
    AUDIT_WRITE_FAILED: "AUDIT_WRITE_FAILED",
  },
  SYSTEM: {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    VALIDATION_ERROR: "VALIDATION_ERROR",
  },
} as const;

type ValueOf<T> = T[keyof T];
type NestedValueOf<T> = ValueOf<{ [K in keyof T]: ValueOf<T[K]> }>;

export type ErrorCode = NestedValueOf<typeof ERROR_CODES>;

export const CORRELATION_ID_HEADER = "x-correlation-id";
