export const PERMISSIONS = {
  PATIENT_READ: "patient.read",
  PATIENT_WRITE: "patient.write",
  PATIENT_MANAGE: "patient.manage",
  PATIENT_NOTES: "patient.notes",
  PATIENT_ATTACHMENTS: "patient.attachments",
  APPOINTMENT_READ: "appointment.read",
  APPOINTMENT_WRITE: "appointment.write",
  NOTES_READ: "notes.read",
  NOTES_WRITE: "notes.write",
  BILLING_READ: "billing.read",
  BILLING_WRITE: "billing.write",
  BILLING_MANAGE: "billing.manage",
  BILLING_ANALYTICS_VIEW: "billing.analytics.view",
  SUBSCRIPTION_READ: "subscription.read",
  SUBSCRIPTION_MANAGE: "subscription.manage",
  SUBSCRIPTION_ADMIN: "subscription.admin",
  PAYMENTS_READ: "payments.read",
  PAYMENTS_WRITE: "payments.write",
  COMMUNICATION_SEND: "communication.send",
  REPORTING_READ: "reporting.read",
  REPORTING_WRITE: "reporting.write",
  REPORTING_MANAGE: "reporting.manage",
  TENANT_MANAGE: "tenant.manage",
  MESSAGING_READ: "messaging.read",
  MESSAGING_WRITE: "messaging.write",
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_WRITE: "notifications.write",
  NOTIFICATION_PROVIDERS_VIEW: "notification.providers.view",
  NOTIFICATION_PROVIDERS_MANAGE: "notification.providers.manage",
  NOTIFICATION_SEND: "notification.send",
  NOTIFICATION_LOGS_VIEW: "notification.logs.view",
  NOTIFICATION_ANALYTICS_VIEW: "notification.analytics.view",
  SEARCH_INDEX: "search.index",
  SEARCH_QUERY: "search.query",
  SEARCH_ADMIN: "search.admin",
  AI_NOTES_READ: "ai.notes.read",
  AI_NOTES_WRITE: "ai.notes.write",
  AI_USE: "ai.use",
  AI_MANAGE: "ai.manage",
  AI_DATASET_VIEW: "ai.dataset.view",
  AI_DATASET_MANAGE: "ai.dataset.manage",
  AI_DATASET_LABEL: "ai.dataset.label",
  AI_TRAINING_VIEW: "ai.training.view",
  AI_TRAINING_MANAGE: "ai.training.manage",
  AI_MODEL_VIEW: "ai.model.view",
  AI_MODEL_MANAGE: "ai.model.manage",
  AI_ADMIN: "ai.admin",
  AI_EVALUATION_RUN: "ai.evaluation.run",
  AI_PROMOTION_MANAGE: "ai.promotion.manage",
  AI_DRIFT_VIEW: "ai.drift.view",
  AI_DRIFT_MITIGATE: "ai.drift.mitigate",
  AUTOMATION_VIEW: "automation.view",
  AUTOMATION_MANAGE: "automation.manage",
  AUTOMATION_MONITOR: "automation.monitor",
  AUTOMATION_VERSIONING: "automation.versioning",
  MARKETPLACE_READ: "marketplace.read",
  MARKETPLACE_WRITE: "marketplace.write",
  MARKETPLACE_MANAGE: "marketplace.manage",
  ENTERPRISE_READ: "enterprise.read",
  ENTERPRISE_WRITE: "enterprise.write",
  ENTERPRISE_MANAGE: "enterprise.manage",
  ORGANIZATION_MANAGE: "organization.manage",
  LOCATION_MANAGE: "location.manage",
  TERMINAL_MANAGE: "terminal.manage",
  ROLE_MANAGE: "role.manage",
  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",
  AUDIT_WRITE_INTERNAL: "audit.write_internal",
  FILES_UPLOAD: "files.upload",
  FILES_VIEW: "files.view",
  FILES_DELETE: "files.delete",
  FILES_DELETE_HARD: "files.delete.hard",
  FILES_GENERATE_THUMBNAIL: "files.generateThumbnail",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export function isPermission(value: unknown): value is Permission {
  return typeof value === "string" && ALL_PERMISSIONS.includes(value as Permission);
}
