import {
  DELETE_LEVEL_PERMISSIONS,
  ORG_LEVEL_PERMISSIONS,
  PLATFORM_LEVEL_PERMISSIONS,
  PLATFORM_PERMISSIONS,
  READ_ONLY_TENANT_PERMISSIONS,
  TENANT_LEVEL_PERMISSIONS,
  type PlatformPermission,
} from "./platform-permissions";
import type { EffectiveRole } from "./platform-roles";

function withoutDeletes(permissions: PlatformPermission[]): PlatformPermission[] {
  return permissions.filter((permission) => !DELETE_LEVEL_PERMISSIONS.includes(permission));
}

const PHARMACY_THERAPIST_PERMISSIONS = [
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_CREATE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_UPDATE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_ISSUE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_READ,
] as const;

const PHARMACY_STAFF_PERMISSIONS = [
  PLATFORM_PERMISSIONS.FULFILLMENT_START,
  PLATFORM_PERMISSIONS.FULFILLMENT_COMPLETE,
  PLATFORM_PERMISSIONS.FULFILLMENT_FAIL,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_READ,
] as const;

const ALL_PHARMACY_PERMISSIONS = [
  ...PHARMACY_THERAPIST_PERMISSIONS,
  ...PHARMACY_STAFF_PERMISSIONS,
] as const;

export const PLATFORM_ROLE_PERMISSIONS: Record<EffectiveRole, PlatformPermission[]> = {
  TENANT_OWNER: [...TENANT_LEVEL_PERMISSIONS],
  ADMIN: withoutDeletes(TENANT_LEVEL_PERMISSIONS),
  STAFF: [
    PLATFORM_PERMISSIONS.PATIENTS_READ,
    PLATFORM_PERMISSIONS.APPOINTMENTS_READ,
    PLATFORM_PERMISSIONS.APPOINTMENTS_WRITE,
    PLATFORM_PERMISSIONS.NOTES_READ,
    PLATFORM_PERMISSIONS.NOTES_WRITE,
    PLATFORM_PERMISSIONS.REPORTS_READ,
    ...PHARMACY_STAFF_PERMISSIONS,
  ],
  THERAPIST: [
    PLATFORM_PERMISSIONS.APPOINTMENTS_READ,
    PLATFORM_PERMISSIONS.APPOINTMENTS_WRITE,
    PLATFORM_PERMISSIONS.NOTES_READ,
    PLATFORM_PERMISSIONS.NOTES_WRITE,
    PLATFORM_PERMISSIONS.AI_NOTES_GENERATE,
    ...PHARMACY_THERAPIST_PERMISSIONS,
  ],
  BILLING_ADMIN: [
    PLATFORM_PERMISSIONS.BILLING_READ,
    PLATFORM_PERMISSIONS.BILLING_PAY,
    PLATFORM_PERMISSIONS.BILLING_MANAGE,
  ],
  READ_ONLY: [...READ_ONLY_TENANT_PERMISSIONS],
  ORG_ADMIN: [...ORG_LEVEL_PERMISSIONS],
  ORG_BILLING_ADMIN: [PLATFORM_PERMISSIONS.ORG_BILLING_MANAGE],
  SUPER_ADMIN: [...PLATFORM_LEVEL_PERMISSIONS],
  PATIENT: [
    PLATFORM_PERMISSIONS.PATIENTS_READ,
    PLATFORM_PERMISSIONS.APPOINTMENTS_READ,
    PLATFORM_PERMISSIONS.NOTES_READ,
    PLATFORM_PERMISSIONS.BILLING_READ,
  ],
  PHARMACY: [
    PLATFORM_PERMISSIONS.PATIENTS_READ,
    PLATFORM_PERMISSIONS.APPOINTMENTS_READ,
    PLATFORM_PERMISSIONS.BILLING_READ,
    PLATFORM_PERMISSIONS.BILLING_PAY,
    ...ALL_PHARMACY_PERMISSIONS,
  ],
};

export function getPlatformPermissionsForRole(role: EffectiveRole): PlatformPermission[] {
  return PLATFORM_ROLE_PERMISSIONS[role] ?? [];
}
