/** Productized platform permission catalog (canonical). */
export const PLATFORM_PERMISSIONS = {
  PATIENTS_READ: "patients.read",
  PATIENTS_WRITE: "patients.write",
  PATIENTS_DELETE: "patients.delete",
  APPOINTMENTS_READ: "appointments.read",
  APPOINTMENTS_WRITE: "appointments.write",
  APPOINTMENTS_CANCEL: "appointments.cancel",
  APPOINTMENTS_COMPLETE: "appointments.complete",
  THERAPISTS_READ: "therapists.read",
  THERAPISTS_WRITE: "therapists.write",
  THERAPISTS_SCHEDULE: "therapists.schedule",
  STAFF_READ: "staff.read",
  STAFF_WRITE: "staff.write",
  STAFF_ROLES_ASSIGN: "staff.roles.assign",
  BILLING_READ: "billing.read",
  BILLING_PAY: "billing.pay",
  BILLING_MANAGE: "billing.manage",
  NOTES_READ: "notes.read",
  NOTES_WRITE: "notes.write",
  NOTES_DELETE: "notes.delete",
  REPORTS_READ: "reports.read",
  SETTINGS_READ: "settings.read",
  SETTINGS_WRITE: "settings.write",
  MESSAGING_READ: "messaging.read",
  MESSAGING_WRITE: "messaging.write",
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_WRITE: "notifications.write",
  NOTIFICATION_PROVIDERS_VIEW: "notification.providers.view",
  NOTIFICATION_PROVIDERS_MANAGE: "notification.providers.manage",
  NOTIFICATION_LOGS_VIEW: "notification.logs.view",
  NOTIFICATION_ANALYTICS_VIEW: "notification.analytics.view",
  NOTIFICATION_SEND: "notification.send",
  FILES_VIEW: "files.view",
  FILES_UPLOAD: "files.upload",
  FILES_DELETE: "files.delete",
  AI_NOTES_GENERATE: "ai.notes.generate",
  AI_NOTES_MANAGE: "ai.notes.manage",
  PRESCRIPTIONS_CREATE: "prescriptions.create",
  PRESCRIPTIONS_UPDATE: "prescriptions.update",
  PRESCRIPTIONS_ISSUE: "prescriptions.issue",
  PRESCRIPTIONS_READ: "prescriptions.read",
  FULFILLMENT_START: "fulfillment.start",
  FULFILLMENT_COMPLETE: "fulfillment.complete",
  FULFILLMENT_FAIL: "fulfillment.fail",
  ENTERPRISE_READ: "enterprise.read",
  ENTERPRISE_WRITE: "enterprise.write",
  ENTERPRISE_MANAGE: "enterprise.manage",
  ORG_TENANTS_READ: "org.tenants.read",
  ORG_TENANTS_WRITE: "org.tenants.write",
  ORG_BILLING_MANAGE: "org.billing.manage",
  PLATFORM_USERS_MANAGE: "platform.users.manage",
  PLATFORM_ORGANIZATIONS_MANAGE: "platform.organizations.manage",
  PLATFORM_TENANTS_MANAGE: "platform.tenants.manage",
  PLATFORM_BILLING_METRICS: "platform.billing.metrics",
  PLATFORM_AUDIT_READ: "platform.audit.read",
  PLATFORM_INTEGRATIONS_MANAGE: "platform.integrations.manage",
} as const;

export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[keyof typeof PLATFORM_PERMISSIONS];

export const ALL_PLATFORM_PERMISSIONS = Object.values(PLATFORM_PERMISSIONS);

export const TENANT_LEVEL_PERMISSIONS: PlatformPermission[] = [
  PLATFORM_PERMISSIONS.PATIENTS_READ,
  PLATFORM_PERMISSIONS.PATIENTS_WRITE,
  PLATFORM_PERMISSIONS.PATIENTS_DELETE,
  PLATFORM_PERMISSIONS.APPOINTMENTS_READ,
  PLATFORM_PERMISSIONS.APPOINTMENTS_WRITE,
  PLATFORM_PERMISSIONS.APPOINTMENTS_CANCEL,
  PLATFORM_PERMISSIONS.APPOINTMENTS_COMPLETE,
  PLATFORM_PERMISSIONS.THERAPISTS_READ,
  PLATFORM_PERMISSIONS.THERAPISTS_WRITE,
  PLATFORM_PERMISSIONS.THERAPISTS_SCHEDULE,
  PLATFORM_PERMISSIONS.STAFF_READ,
  PLATFORM_PERMISSIONS.STAFF_WRITE,
  PLATFORM_PERMISSIONS.STAFF_ROLES_ASSIGN,
  PLATFORM_PERMISSIONS.BILLING_READ,
  PLATFORM_PERMISSIONS.BILLING_PAY,
  PLATFORM_PERMISSIONS.BILLING_MANAGE,
  PLATFORM_PERMISSIONS.NOTES_READ,
  PLATFORM_PERMISSIONS.NOTES_WRITE,
  PLATFORM_PERMISSIONS.NOTES_DELETE,
  PLATFORM_PERMISSIONS.REPORTS_READ,
  PLATFORM_PERMISSIONS.SETTINGS_READ,
  PLATFORM_PERMISSIONS.SETTINGS_WRITE,
  PLATFORM_PERMISSIONS.MESSAGING_READ,
  PLATFORM_PERMISSIONS.MESSAGING_WRITE,
  PLATFORM_PERMISSIONS.NOTIFICATIONS_READ,
  PLATFORM_PERMISSIONS.NOTIFICATIONS_WRITE,
  PLATFORM_PERMISSIONS.NOTIFICATION_PROVIDERS_VIEW,
  PLATFORM_PERMISSIONS.NOTIFICATION_PROVIDERS_MANAGE,
  PLATFORM_PERMISSIONS.NOTIFICATION_LOGS_VIEW,
  PLATFORM_PERMISSIONS.NOTIFICATION_ANALYTICS_VIEW,
  PLATFORM_PERMISSIONS.NOTIFICATION_SEND,
  PLATFORM_PERMISSIONS.FILES_VIEW,
  PLATFORM_PERMISSIONS.FILES_UPLOAD,
  PLATFORM_PERMISSIONS.FILES_DELETE,
  PLATFORM_PERMISSIONS.AI_NOTES_GENERATE,
  PLATFORM_PERMISSIONS.AI_NOTES_MANAGE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_CREATE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_UPDATE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_ISSUE,
  PLATFORM_PERMISSIONS.PRESCRIPTIONS_READ,
  PLATFORM_PERMISSIONS.FULFILLMENT_START,
  PLATFORM_PERMISSIONS.FULFILLMENT_COMPLETE,
  PLATFORM_PERMISSIONS.FULFILLMENT_FAIL,
  PLATFORM_PERMISSIONS.ENTERPRISE_READ,
  PLATFORM_PERMISSIONS.ENTERPRISE_WRITE,
];

export const ORG_LEVEL_PERMISSIONS: PlatformPermission[] = [
  PLATFORM_PERMISSIONS.ORG_TENANTS_READ,
  PLATFORM_PERMISSIONS.ORG_TENANTS_WRITE,
  PLATFORM_PERMISSIONS.ORG_BILLING_MANAGE,
  PLATFORM_PERMISSIONS.BILLING_READ,
  PLATFORM_PERMISSIONS.BILLING_PAY,
];

export const PLATFORM_LEVEL_PERMISSIONS: PlatformPermission[] = [
  PLATFORM_PERMISSIONS.PLATFORM_USERS_MANAGE,
  PLATFORM_PERMISSIONS.PLATFORM_ORGANIZATIONS_MANAGE,
  PLATFORM_PERMISSIONS.PLATFORM_TENANTS_MANAGE,
  PLATFORM_PERMISSIONS.PLATFORM_BILLING_METRICS,
  PLATFORM_PERMISSIONS.PLATFORM_AUDIT_READ,
  PLATFORM_PERMISSIONS.PLATFORM_INTEGRATIONS_MANAGE,
];

export const DELETE_LEVEL_PERMISSIONS: PlatformPermission[] = [
  PLATFORM_PERMISSIONS.PATIENTS_DELETE,
  PLATFORM_PERMISSIONS.NOTES_DELETE,
];

export const READ_ONLY_TENANT_PERMISSIONS: PlatformPermission[] = TENANT_LEVEL_PERMISSIONS.filter(
  (permission) =>
    permission.endsWith(".read") ||
    permission === PLATFORM_PERMISSIONS.THERAPISTS_SCHEDULE ||
    permission === PLATFORM_PERMISSIONS.REPORTS_READ ||
    permission === PLATFORM_PERMISSIONS.PRESCRIPTIONS_READ,
);

/** Legacy dot-notation permissions map to productized permissions. */
export const LEGACY_PERMISSION_ALIASES: Record<string, PlatformPermission> = {
  "patient.read": PLATFORM_PERMISSIONS.PATIENTS_READ,
  "patient.view": PLATFORM_PERMISSIONS.PATIENTS_READ,
  "patient.write": PLATFORM_PERMISSIONS.PATIENTS_WRITE,
  "patient.edit": PLATFORM_PERMISSIONS.PATIENTS_WRITE,
  "patient.manage": PLATFORM_PERMISSIONS.PATIENTS_WRITE,
  "patient.attachments": PLATFORM_PERMISSIONS.PATIENTS_READ,
  "appointment.read": PLATFORM_PERMISSIONS.APPOINTMENTS_READ,
  "appointment.write": PLATFORM_PERMISSIONS.APPOINTMENTS_WRITE,
  "appointment.manage": PLATFORM_PERMISSIONS.APPOINTMENTS_WRITE,
  "billing.read": PLATFORM_PERMISSIONS.BILLING_READ,
  "billing.write": PLATFORM_PERMISSIONS.BILLING_PAY,
  "billing.manage": PLATFORM_PERMISSIONS.BILLING_MANAGE,
  "billing.analytics.view": PLATFORM_PERMISSIONS.PLATFORM_BILLING_METRICS,
  "reporting.read": PLATFORM_PERMISSIONS.REPORTS_READ,
  "ai.notes.read": PLATFORM_PERMISSIONS.NOTES_READ,
  "ai.notes.write": PLATFORM_PERMISSIONS.AI_NOTES_GENERATE,
  "ai.use": PLATFORM_PERMISSIONS.AI_NOTES_GENERATE,
  "ai.manage": PLATFORM_PERMISSIONS.AI_NOTES_MANAGE,
  "organization.manage": PLATFORM_PERMISSIONS.ORG_TENANTS_WRITE,
  "user.manage": PLATFORM_PERMISSIONS.STAFF_WRITE,
  "settings.manage": PLATFORM_PERMISSIONS.SETTINGS_WRITE,
  "location.manage": PLATFORM_PERMISSIONS.SETTINGS_WRITE,
  "terminal.manage": PLATFORM_PERMISSIONS.SETTINGS_WRITE,
  "tenant.manage": PLATFORM_PERMISSIONS.SETTINGS_WRITE,
  "role.manage": PLATFORM_PERMISSIONS.STAFF_ROLES_ASSIGN,
  "audit.view": PLATFORM_PERMISSIONS.PLATFORM_AUDIT_READ,
  "notification.providers.view": PLATFORM_PERMISSIONS.SETTINGS_READ,
  "notification.providers.manage": PLATFORM_PERMISSIONS.SETTINGS_WRITE,
  "notification.logs.view": PLATFORM_PERMISSIONS.SETTINGS_READ,
  "notification.analytics.view": PLATFORM_PERMISSIONS.SETTINGS_READ,
  "notification.send": PLATFORM_PERMISSIONS.SETTINGS_WRITE,
};

export function normalizePermissionKey(permission: string): string {
  return LEGACY_PERMISSION_ALIASES[permission] ?? permission;
}

export function isPlatformPermission(value: string): value is PlatformPermission {
  return ALL_PLATFORM_PERMISSIONS.includes(value as PlatformPermission);
}
