import { normalizePermissionKey } from "./platform-permissions";
import { getPlatformPermissionsForRole } from "./platform-role-permissions";
import { normalizeEffectiveRole } from "./platform-roles";
import { PERMISSIONS, type Permission } from "./permissions";
import { ROLES, isSystemRole, type SecurityRole } from "./roles";

export type SecurityUser = {
  userId: string;
  tenantId?: string;
  organizationId?: string | null;
  role: SecurityRole;
  effectiveRole?: string;
  permissions?: string[];
  email?: string;
};

const LEGACY_ROLE_PERMISSIONS: Record<SecurityRole, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  SYSTEM: Object.values(PERMISSIONS),
  TENANT_OWNER: Object.values(PERMISSIONS).filter(
    (permission) => permission !== PERMISSIONS.AUDIT_WRITE_INTERNAL,
  ),
  OWNER: Object.values(PERMISSIONS).filter(
    (permission) => permission !== PERMISSIONS.AUDIT_WRITE_INTERNAL,
  ),
  ADMIN: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.FILES_UPLOAD,
    PERMISSIONS.FILES_VIEW,
    PERMISSIONS.FILES_DELETE,
    PERMISSIONS.FILES_DELETE_HARD,
    PERMISSIONS.LOCATION_MANAGE,
    PERMISSIONS.TERMINAL_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE,
    PERMISSIONS.PATIENT_MANAGE,
    PERMISSIONS.PATIENT_NOTES,
    PERMISSIONS.PATIENT_ATTACHMENTS,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.NOTES_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.BILLING_ANALYTICS_VIEW,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.SUBSCRIPTION_ADMIN,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_WRITE,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.REPORTING_READ,
    PERMISSIONS.REPORTING_WRITE,
    PERMISSIONS.REPORTING_MANAGE,
    PERMISSIONS.TENANT_MANAGE,
    PERMISSIONS.MESSAGING_READ,
    PERMISSIONS.MESSAGING_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.AI_NOTES_READ,
    PERMISSIONS.AI_NOTES_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_MANAGE,
    PERMISSIONS.AI_DATASET_VIEW,
    PERMISSIONS.AI_DATASET_MANAGE,
    PERMISSIONS.AI_DATASET_LABEL,
    PERMISSIONS.AI_TRAINING_VIEW,
    PERMISSIONS.AI_TRAINING_MANAGE,
    PERMISSIONS.AI_MODEL_VIEW,
    PERMISSIONS.AI_MODEL_MANAGE,
    PERMISSIONS.AI_ADMIN,
    PERMISSIONS.AI_EVALUATION_RUN,
    PERMISSIONS.AI_PROMOTION_MANAGE,
    PERMISSIONS.AI_DRIFT_VIEW,
    PERMISSIONS.AI_DRIFT_MITIGATE,
    PERMISSIONS.AUTOMATION_VIEW,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.AUTOMATION_MONITOR,
    PERMISSIONS.AUTOMATION_VERSIONING,
    PERMISSIONS.MARKETPLACE_READ,
    PERMISSIONS.MARKETPLACE_WRITE,
    PERMISSIONS.ENTERPRISE_READ,
    PERMISSIONS.ENTERPRISE_WRITE,
  ],
  THERAPIST: [
    PERMISSIONS.FILES_UPLOAD,
    PERMISSIONS.FILES_VIEW,
    PERMISSIONS.FILES_DELETE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_WRITE,
    PERMISSIONS.PATIENT_NOTES,
    PERMISSIONS.PATIENT_ATTACHMENTS,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.NOTES_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.REPORTING_READ,
    PERMISSIONS.REPORTING_WRITE,
    PERMISSIONS.REPORTING_MANAGE,
    PERMISSIONS.MESSAGING_READ,
    PERMISSIONS.MESSAGING_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.AI_NOTES_READ,
    PERMISSIONS.AI_NOTES_WRITE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_MANAGE,
  ],
  STAFF: [
    PERMISSIONS.FILES_UPLOAD,
    PERMISSIONS.FILES_VIEW,
    PERMISSIONS.FILES_DELETE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_NOTES,
    PERMISSIONS.PATIENT_ATTACHMENTS,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.MESSAGING_READ,
    PERMISSIONS.MESSAGING_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.REPORTING_READ,
  ],
  BILLING_ADMIN: [
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_WRITE,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
  ],
  READ_ONLY: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.REPORTING_READ,
    PERMISSIONS.MESSAGING_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  ORG_ADMIN: [PERMISSIONS.ORGANIZATION_MANAGE, PERMISSIONS.BILLING_MANAGE],
  ORG_BILLING_ADMIN: [PERMISSIONS.BILLING_MANAGE, PERMISSIONS.SUBSCRIPTION_MANAGE],
  PATIENT: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.MESSAGING_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  PHARMACY: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.MESSAGING_READ,
    PERMISSIONS.MESSAGING_WRITE,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.REPORTING_READ,
    PERMISSIONS.MARKETPLACE_READ,
  ],
};

export class RbacService {
  hasRole(user: SecurityUser, role: SecurityRole): boolean {
    return user.role === role;
  }

  hasPermission(user: SecurityUser, permission: Permission | string): boolean {
    const normalized = normalizePermissionKey(permission);
    if (user.permissions?.includes(normalized) || user.permissions?.includes(permission)) {
      return true;
    }

    const effective = normalizeEffectiveRole(user.effectiveRole ?? user.role);
    if (effective === "SUPER_ADMIN") {
      return true;
    }

    if (effective) {
      const platformPermissions = getPlatformPermissionsForRole(effective);
      if (platformPermissions.includes(normalized as never)) {
        return true;
      }
    }

    const legacy = getPermissionsForRole(user.role);
    return legacy.includes(permission as Permission) || legacy.includes(normalized as Permission);
  }

  enforceTenantIsolation(user: SecurityUser, tenantId: string): boolean {
    if (isSystemRole(user.role)) {
      return true;
    }
    return user.tenantId === tenantId;
  }

  assertPermission(user: SecurityUser, permission: Permission | string): void {
    if (!this.hasPermission(user, permission)) {
      throw new Error(`Missing permission: ${permission}`);
    }
  }

  assertTenantAccess(user: SecurityUser, tenantId: string): void {
    if (!this.enforceTenantIsolation(user, tenantId)) {
      throw new Error("Cross-tenant access is not allowed");
    }
  }
}

export function getPermissionsForRole(role: SecurityRole): Permission[] {
  const effective = normalizeEffectiveRole(role);
  if (effective) {
    return getPlatformPermissionsForRole(effective) as unknown as Permission[];
  }
  return LEGACY_ROLE_PERMISSIONS[role] ?? [];
}

export const rbacService = new RbacService();
