import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const PAYMENT_SERVICE_NAME = "payment-service";

export const DEFAULT_CURRENCY = "USD";

export const PAYMENT_EVENTS = {
  PAYMENT_INTENT_CREATED: EVENT_TYPES.PAYMENT_INTENT_CREATED,
  PAYMENT_SUCCEEDED: EVENT_TYPES.PAYMENT_SUCCEEDED,
  PAYMENT_FAILED: EVENT_TYPES.PAYMENT_FAILED,
  PAYMENT_CANCELLED: EVENT_TYPES.PAYMENT_CANCELLED,
  REFUND_CREATED: EVENT_TYPES.REFUND_CREATED,
  PAYOUT_CREATED: EVENT_TYPES.PAYOUT_CREATED,
  LEDGER_ENTRY_CREATED: EVENT_TYPES.LEDGER_ENTRY_CREATED,
} as const;
