export const DB_ERROR_CODES = {
  UNIQUE_CONSTRAINT: "UNIQUE_CONSTRAINT",
  FOREIGN_KEY_CONSTRAINT: "FOREIGN_KEY_CONSTRAINT",
  RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
  INVALID_INPUT: "INVALID_INPUT",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
} as const;

export type DbErrorCode = (typeof DB_ERROR_CODES)[keyof typeof DB_ERROR_CODES];

export const TENANT_ID_FIELD = "tenantId";
export const DELETED_AT_FIELD = "deletedAt";
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export const PRISMA_ERROR_CODE_MAP: Record<string, DbErrorCode> = {
  P2002: DB_ERROR_CODES.UNIQUE_CONSTRAINT,
  P2003: DB_ERROR_CODES.FOREIGN_KEY_CONSTRAINT,
  P2014: DB_ERROR_CODES.FOREIGN_KEY_CONSTRAINT,
  P2025: DB_ERROR_CODES.RECORD_NOT_FOUND,
};
