import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const MESSAGING_SERVICE_NAME = "messaging-service";

export const DEFAULT_MESSAGES_PAGE_SIZE = 50;

export const TYPING_INDICATOR_TTL_SECONDS = 5;

export const MESSAGING_EVENTS = {
  CONVERSATION_CREATED: EVENT_TYPES.MESSAGING_CONVERSATION_CREATED,
  MESSAGE_CREATED: EVENT_TYPES.MESSAGING_MESSAGE_CREATED,
  MESSAGE_READ: EVENT_TYPES.MESSAGING_MESSAGE_READ,
  TYPING: EVENT_TYPES.MESSAGING_TYPING,
} as const;
