apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  NODE_ENV: production
  LOG_LEVEL: warn
  environment: production
  API_GATEWAY_URL: https://api.ordella-physio.com
  CORS_ORIGIN: https://app.ordella-physio.com
