apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ordella-production

resources:
  - ../../base

patches:
  - path: configmap-production.yaml
  - path: secret-production.yaml
  - path: ingress-production.yaml

commonLabels:
  environment: production

replicas:
  - name: api-gateway
    count: 3
  - name: frontend-web
    count: 3

images:
  - name: ghcr.io/ordella/api-gateway
    newTag: production
  - name: ghcr.io/ordella/auth-service
    newTag: production
  - name: ghcr.io/ordella/tenant-service
    newTag: production
  - name: ghcr.io/ordella/patient-service
    newTag: production
  - name: ghcr.io/ordella/appointment-service
    newTag: production
  - name: ghcr.io/ordella/notes-service
    newTag: production
  - name: ghcr.io/ordella/billing-service
    newTag: production
  - name: ghcr.io/ordella/payment-service
    newTag: production
  - name: ghcr.io/ordella/communication-service
    newTag: production
  - name: ghcr.io/ordella/reporting-service
    newTag: production
  - name: ghcr.io/ordella/event-bus-service
    newTag: production
  - name: ghcr.io/ordella/frontend-web
    newTag: production
