apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ordella-production

resources:
  - ../../base
  - traefik-values-production.yaml

commonLabels:
  environment: production

replicas:
  - name: traefik
    count: 2
