import { TENANT_HEADER, CORRELATION_ID_HEADER } from "@ordella/middleware";
import { EVENT_TYPES } from "@ordella/shared";

export { TENANT_HEADER, CORRELATION_ID_HEADER };

export const COMMUNICATION_SERVICE_NAME = "communication-service";

export const COMMUNICATION_EVENTS = {
  NOTIFICATION_CREATED: EVENT_TYPES.NOTIFICATION_CREATED,
  NOTIFICATION_SENT: EVENT_TYPES.NOTIFICATION_SENT,
  NOTIFICATION_FAILED: EVENT_TYPES.NOTIFICATION_FAILED,
  NOTIFICATION_CANCELLED: EVENT_TYPES.NOTIFICATION_CANCELLED,
  REMINDER_CREATED: EVENT_TYPES.REMINDER_CREATED,
  REMINDER_CANCELLED: EVENT_TYPES.REMINDER_CANCELLED,
} as const;
