apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  labels:
    app: frontend-web
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend-web
  ports:
    - name: http
      port: 80
      targetPort: 3010
