apiVersion: v1
kind: Service
metadata:
  name: notes-service
  labels:
    app: notes-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: notes-service
  ports:
    - name: http
      port: 3055
      targetPort: 3055
