apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  labels:
    app: tenant-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: tenant-service
  ports:
    - name: http
      port: 3052
      targetPort: 3052
